### ISSUE TITLE
PHP Fatal error:  Uncaught exception

### ISSUE THREAD

**Issue by executivoclub** [rhayun/php-ade#1]
Hello,

I'm getting a problem when run the script, as the trace below shows:
```

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'file_get_contents(https://www.adultdvdempire.com/1926052/angela-loves-anal-porn-movies.html): failed to open stream: operation failed' in /var/www/adultdvd/vendor/kriswallsmith/buzz/lib/Buzz/Client/FileGetContents.php:50
Stack trace:
#0 /var/www/adultdvd/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(136): Buzz\Client\FileGetContents->send(Object(Buzz\Message\Request), Object(Buzz\Message\Response))
#1 /var/www/adultdvd/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(85): Buzz\Browser->send(Object(Buzz\Message\Request))
#2 /var/www/adultdvd/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(31): Buzz\Browser->call('https://www.adu...', 'GET', Array)
#3 /var/www/adultdvd/src/ADE/Movie.php(152): Buzz\Browser->get('https://www.adu...', Array)
#4 /var/www/adultdvd/src/ADE/Movie.php(27): ADE\Movie->getCrawler()
#5 /var/www/adultdvd/teste.php(4): ADE\Movie->__construct('https://www.adu...')
#6 {main}
  thrown in /var/www/adultdvd/vendor/kriswallsmith/buzz/lib/Buzz/Client/FileGetContents.php on line 50
```

This code still working?

Regards,

**Comment by rhayun** [comment]
Hi,
sorry for the delay
Yes this code is working - i am not sure why you get this error - i believe its something with your server configuration - maybe some limitation in your php.ini

**Comment by rhayun** [comment]
Update this package to work with php 7 and above - should fix your error
